### PR TITLE
Allow get access to LazyOptionals in ICapabilityHolder components

### PR DESCRIPTION
**Pull request by FreneticScribbler**
I want to be able to do this:
`this.multiInventoryComponent.getLazyOptionals().forEach(o -> o.invalidate());` `this.multiTankComponent.getLazyOptionals().forEach(o -> o.invalidate());`

Where necessary (when invalidateCaps is called from my tile) to neatly invalidate all of my machine capabilities. Out of curiosity, how does stuff that depends on ActiveTile handle this? Manually?

### CODE REVIEW

**Comment by Buuz135** [comment]
Currently it doesnt invalidate, can you add it to the pr too?

**Comment by FreneticScribbler** [comment]
Yep will do :+1:

**Comment by FreneticScribbler** [comment]
Because invalidateCaps is called on chunk unload I'm unclear if I need to manually rebuild the optionals when the chunk is reloaded. Since I don't use ActiveTile I need someone else who does to test it...

**Comment by Buuz135** [comment]
When a chunk loads the tile gets constructed again. So it doesnt need to get rebuilt.

**Review by Buuz135 — APPROVED** [review]

**Pull request merged**
